# Generated by Django 5.0 on 2024-01-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Botinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('info', models.TextField(verbose_name="Botga yozilgan ma'lumotlar")),
                ('email_pochta', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='ContactModel',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitemmodel',
            name='product',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='owner',
        ),
        migrations.DeleteModel(
            name='LocationModel',
        ),
        migrations.DeleteModel(
            name='OrderitemModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
        migrations.DeleteModel(
            name='OrderModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
