# Generated by Django 4.2.7 on 2023-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatheModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birinchi_son', models.IntegerField(default=13, verbose_name='Birinchi son')),
                ('ikkinchi_son', models.IntegerField(default=15, verbose_name='Ikkinchi son')),
                ('natija', models.IntegerField(default=28, verbose_name='Natija')),
            ],
            options={
                'verbose_name': 'Misol',
                'verbose_name_plural': 'Misollar',
            },
        ),
    ]
