# Generated by Django 4.2.7 on 2023-11-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misol', '0002_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Tetslar'},
        ),
    ]
