# Generated by Django 4.2.7 on 2023-11-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misol', '0003_alter_testmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Test rasmi'),
        ),
    ]
