# Generated by Django 4.2.7 on 2023-11-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YangilikModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Mavzusi nomalum xabar', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('photos', models.ImageField(default='static/images/default.jpg', upload_to='photos/%Y/%m/%d')),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
