# Generated by Django 4.2.7 on 2023-11-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yangilikmodel',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
