# Generated by Django 4.2.7 on 2023-11-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_yangilikmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yangilikmodel',
            name='photos',
            field=models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d'),
        ),
    ]
