# Generated by Django 5.0.1 on 2024-01-10 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Brand nomi')),
            ],
            options={
                'verbose_name': 'Brand ',
                'verbose_name_plural': 'Brandlar',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Mashina nomi')),
                ('price', models.IntegerField(verbose_name='Narxi')),
                ('color', models.CharField(max_length=30, null=True, verbose_name='Rangi')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.branchmodel')),
            ],
            options={
                'verbose_name': 'Mashina ',
                'verbose_name_plural': 'Mashinalar ',
            },
        ),
        migrations.CreateModel(
            name='EmployeesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof', models.CharField(max_length=30, verbose_name='Kasbi')),
                ('name', models.CharField(max_length=30, verbose_name='Ismi')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carapp.branchmodel')),
            ],
            options={
                'verbose_name': 'Ishchi ',
                'verbose_name_plural': 'Ishchilar ',
            },
        ),
    ]
