# Generated by Django 5.0.1 on 2024-01-11 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0003_brand_brand_locations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='BrandModel',
        ),
        migrations.RenameModel(
            old_name='Car',
            new_name='CarModel',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='EmployeesModel',
        ),
    ]
