# Generated by Django 5.0.1 on 2024-01-13 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0006_rename_carmodel_car_rename_employeesmodel_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Brand ', 'verbose_name_plural': 'Brandlar '},
        ),
    ]
