# Generated by Django 4.2.7 on 2023-11-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarlavha', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
                ('model', models.TextField(max_length=100)),
                ('year', models.IntegerField(default=2022)),
                ('price', models.IntegerField()),
                ('auto_pictures', models.ImageField(default='Mashina rasmi mavjud emas', upload_to='photos/%Y/%m/%d')),
            ],
        ),
    ]
