# Generated by Django 4.2.7 on 2023-11-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avto_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avto',
            options={'verbose_name': 'Mashinalar haqida'},
        ),
    ]
