# Generated by Django 4.2.7 on 2023-11-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avto_app', '0002_alter_avto_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avto',
            new_name='AvtoModel',
        ),
    ]
