# Generated by Django 5.0.1 on 2024-01-11 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BranchModel',
            new_name='Brand',
        ),
        migrations.RenameModel(
            old_name='CarModel',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='EmployeesModel',
            new_name='Employees',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='branch_id',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='branch_id',
            new_name='brand_id',
        ),
    ]
