# Generated by Django 5.0.1 on 2024-01-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_rename_branchmodel_brand_rename_carmodel_car_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='brand_locations',
            field=models.CharField(default=2, max_length=30, verbose_name='Brand joylashgan davlat'),
            preserve_default=False,
        ),
    ]
