# Generated by Django 5.0.1 on 2024-01-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0004_rename_brand_brandmodel_rename_car_carmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrandModel',
            new_name='Brand',
        ),
    ]
