# Generated by Django 5.0.1 on 2024-01-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0005_rename_brandmodel_brand'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarModel',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='EmployeesModel',
            new_name='Employees',
        ),
    ]
