# Generated by Django 4.2.7 on 2023-11-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['created_at', 'content'], 'verbose_name': 'Veb sayt sahifa', 'verbose_name_plural': 'Veb sayt sahifalari'},
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='photos',
            field=models.ImageField(default='rasm mavjud emas', upload_to='photos/%Y/%m/%d'),
        ),
    ]
