# Generated by Django 4.2.6 on 2023-12-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=40, verbose_name='Familiyasi')),
                ('region', models.CharField(max_length=20, verbose_name='Viloyat')),
                ('city', models.CharField(max_length=30, verbose_name='Shahar')),
                ('company_name', models.CharField(max_length=40, verbose_name='Dorixona nomi')),
                ('address', models.TextField(verbose_name='Manzil')),
                ('posta_code', models.IntegerField(verbose_name='Pochta kodi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Telefon nomer')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
            },
        ),
        migrations.CreateModel(
            name='PharmaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharma_name', models.CharField(max_length=50, verbose_name='Dori nomi')),
                ('pharma_about', models.TextField(blank=True, verbose_name='Dori haqida')),
                ('pharma_price', models.IntegerField(verbose_name='Narhi')),
            ],
            options={
                'verbose_name': 'Dori',
                'verbose_name_plural': 'Dorilar',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ismi')),
                ('last_name', models.CharField(max_length=40, verbose_name='Familiyasi')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.TextField(blank=True, verbose_name='Qisqacha')),
                ('message', models.TextField(blank=True, verbose_name='Xabar')),
            ],
            options={
                'verbose_name': "Kontakt ma'lumoti",
                'verbose_name_plural': "Kontakt ma'lumotlari",
            },
        ),
    ]
