# Generated by Django 4.2.6 on 2023-12-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverymodel',
            options={'verbose_name': 'Buyurtma ', 'verbose_name_plural': 'Buyurtmalar '},
        ),
    ]
