# Generated by Django 4.2.7 on 2023-12-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('egasi', models.CharField(default='Suhrob', max_length=20, verbose_name='Egasi')),
                ('model', models.CharField(default='BMW X6', max_length=30, verbose_name='Model')),
                ('narxi', models.IntegerField(default=500000, verbose_name='Narxi')),
                ('rasmi', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
