# Generated by Django 5.0.1 on 2024-01-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ism')),
                ('l_name', models.CharField(max_length=30, verbose_name='Familiya')),
                ('gender', models.CharField(max_length=10, verbose_name='Jins')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('contact_add', models.IntegerField(verbose_name='Nomer')),
                ('cust_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cust_pass', models.CharField(max_length=50, verbose_name='Pass')),
            ],
            options={
                'verbose_name': 'Customer table ',
                'verbose_name_plural': 'Customer tables ',
            },
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_category', models.CharField(max_length=50, verbose_name='Kategoriya')),
                ('name', models.CharField(max_length=30, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Haqida')),
                ('price', models.IntegerField(verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Medicines table ',
                'verbose_name_plural': 'Medicines tables ',
            },
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Ism')),
                ('l_name', models.CharField(max_length=30, verbose_name='Familiya')),
                ('gender', models.CharField(max_length=10, verbose_name='Jins')),
                ('age', models.IntegerField(verbose_name='Yosh')),
                ('contact_add', models.IntegerField(verbose_name='Nomer')),
                ('admin_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('admin_pass', models.CharField(max_length=50, verbose_name='Pass')),
            ],
            options={
                'verbose_name': 'Pharmacist table ',
                'verbose_name_plural': 'Pharmacist tables ',
            },
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Soni')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan kun')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.medicines')),
            ],
            options={
                'verbose_name': 'Purchasing table ',
                'verbose_name_plural': 'Purchasing tables ',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Soni')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.IntegerField(verbose_name='Sotilgan maxsulot soni')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.customer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.medicines')),
                ('pharm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.pharmacist')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.purchasing')),
            ],
            options={
                'verbose_name': 'Sales table ',
                'verbose_name_plural': 'Sales tables ',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Sotilgan kun')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.customer')),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.purchasing')),
                ('sales_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.sales')),
            ],
            options={
                'verbose_name': 'Reports table ',
                'verbose_name_plural': 'Reports tables ',
            },
        ),
    ]
