# Generated by Django 5.0.1 on 2024-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicines',
            name='med_category',
            field=models.CharField(choices=[('active', 'Aktiv'), ('noactive', 'Noaktive')], default='active', max_length=8, verbose_name='Kategoriya'),
        ),
    ]
