# Generated by Django 5.0.1 on 2024-01-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0002_alter_medicines_med_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasing',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='medicines',
            name='med_category',
            field=models.CharField(choices=[('kapsula', 'Kapsula shaklda'), ('qattiq', 'Qattiq shaklda'), ('kukun', 'Kukun shaklda'), ('suyuq', 'Suyuq shaklda')], default='qattiq shaklda', max_length=20, verbose_name='Kategoriya'),
        ),
    ]
