# Generated by Django 5.0.1 on 2024-01-13 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0003_rename_data_purchasing_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='data',
            new_name='date',
        ),
    ]
