# Generated by Django 4.2.7 on 2023-11-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, default='images/icon/logo_1.png', upload_to='images/icon')),
                ('content', models.TextField(blank=True, default="Bu haqida to'liq ma'lumot topa olmadik")),
            ],
        ),
    ]
