# Generated by Django 4.2.7 on 2023-11-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_lesson_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson_9',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediauser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
