# Generated by Django 4.2.7 on 2023-11-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_aboutme_contact_rasmlar_alter_lesson_9_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Rasmi_2'),
        ),
    ]
